### ISSUE TITLE
actions中调用mutations没有生效

### ISSUE THREAD

**Issue by guyue88** [tinajs/tina-hackernews#1]
一个奇怪的问题：actions中必须return commit(xxxx)才能使commit生效。

这种情况下，dispatch与commit都可以更改数据。
![image](https://user-images.githubusercontent.com/12598256/40215059-ddaead96-5a90-11e8-8af8-0ac9604b6d71.png)

这种情况下，dispatch调用其他action可以成功，但是commit调用mutation是不生效的。
![image](https://user-images.githubusercontent.com/12598256/40215069-e9ce0748-5a90-11e8-8426-1b5f0c3b120d.png)

麻烦看下！

**Comment by guyue88** [comment]
提错地方~~~

**Comment by imyelo** [comment]
moved to https://github.com/tinajs/tinax/issues/1
